#!/bin/bash

export WEBEXAMPLE_MAIN_DIR="$PWD"

export WEBEXAMPLE_DB_SQL_MASTER_NAME=webexample
export WEBEXAMPLE_DB_SQL_MASTER_HOST='127.0.0.1'
export WEBEXAMPLE_DB_SQL_MASTER_PORT=35432
export WEBEXAMPLE_DB_SQL_MASTER_USER=webexample
export WEBEXAMPLE_DB_SQL_MASTER_PASS=webexamplepwd
export WEBEXAMPLE_DB_REDIS_MASTER_HOST='127.0.0.1'
export WEBEXAMPLE_DB_REDIS_MASTER_PORT=36379

# setup the migrations dir:
export WEBEXAMPLE_BUNDLER_MIGRATIONS_DST="$WEBEXAMPLE_MAIN_DIR/dbmigrations"

# Use the console mailer to see the output of the emails in stdout
export WEBEXAMPLE_MAILER_PREFERRED=console
export WEBEXAMPLE_MAILER_LOGS=true

# notifications config
export WEBEXAMPLE_NOTIFICATIONS_TEMPLATES_DIR="$WEBEXAMPLE_MAIN_DIR/notifications/templates"

export WEBEXAMPLE_WEB_STATICPATH="$WEBEXAMPLE/static"
export WEBEXAMPLE_WEB_TMPLPATH="$WEBEXAMPLE/html_templates"
export WEBEXAMPLE_WEB_EXTRATMPLPATH="$WEBEXAMPLE"

export WEBEXAMPLE_GINFW_SESSION_CSRFSECRET="ThisIsTheCSRFSecretToken"
export WEBEXAMPLE_GINFW_SESSION_SECRETKEYPAIR="ThisIsSecretKeyPair"
