services:
  hfw_test_db:
    image: postgres
    ports:
      - "0.0.0.0::5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: hfwtest
      POSTGRES_DB: hfwtest
  hfw_test_redis:
    image: redis
    ports:
      - "0.0.0.0::6279"
