version: "2.1"
services:
  prometheus:
    container_name: "prometheus_example"
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"
  loki:
    container_name: "loki_example"
    image: "grafana/loki:latest"
    healthcheck:
      test: [CMD, wget, --spider, -S, http://localhost:3100/ready]
    ports:
      - "3100:3100"
  promtail:
    container_name: "promtail_example"
    image: "grafana/promtail:latest"
    ports:
      - "3200:3200"
    volumes:
      - "./conf/promtail.yml:/etc/prometheus/promtail.yml"
      - "./tmp:/var/log/tmp"
    command: "-config.file=/etc/prometheus/promtail.yml"
  jaeger:
    container_name: "jaeger_example"
    image: "jaegertracing/all-in-one:latest"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  grafana:
    container_name: "grafana_example"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
