volumes:
  vol_obs_example_grafana:
  vol_obs_example_tempo:
services:
  prometheus:
    container_name: "prometheus_example"
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - "./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  loki:
    container_name: "loki_example"
    image: "grafana/loki:latest"
    healthcheck:
      test: [CMD, wget, --spider, -S, http://localhost:3100/ready]
    ports:
      - "3100:3100"
  promtail:
    container_name: "promtail_example"
    image: "grafana/promtail:latest"
    ports:
      - "3050:3050"
    volumes:
      - "./conf/promtail/promtail.yml:/etc/prometheus/promtail.yml"
      - "./tmp:/var/log/tmp"
    command: "-config.file=/etc/prometheus/promtail.yml"
  tempo:
    image: grafana/tempo:latest
    domainname: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "vol_obs_example_tempo:/tmp/tempo"
    ports:
      - "3200:3200"     # tempo
      - "9095:9095"     # tempo grpc
      - "54317:4317"    # otlp grpc
      - "54318:4318"    # otlp http
  grafana:
    container_name: "grafana_example"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: hfw
      GF_SECURITY_ADMIN_PASSWORD: hfw
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "vol_obs_example_grafana:/var/lib/grafana"
      - "./conf/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./conf/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./conf/grafana/data/dashboards:/var/lib/grafana/dashboards"
    depends_on:
      - prometheus
      - loki
      - promtail
      - tempo
  mailcatcher:
    container_name: "mailcatcher_example"
    image: "sj26/mailcatcher:latest"
    ports: 
      - "1080:1080"
      - "1025:1025"
