name: Run Tests
on: [pull_request, workflow_dispatch]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "run test"
        run: make dctest
